version: '3.1'

services:

  faraway-backend:
    image: ${BE_IMAGE}
    ports:
      - 4000:4000
    restart: on-failure:5

  faraway-front-end:
    image: ${FE_IMAGE}
    ports:
      - 3000:3000
    restart: on-failure:5