name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      fe_image:
        default: 'evercoinx/faraway:nft-collection-deployer-frontend'
        required: true
        type: string
      be_image:
        default: 'evercoinx/faraway:nft-collection-deployer-backend'
        required: true
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install Chrome
      uses: browser-actions/setup-chrome@113
    - run: chrome --version
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Build Applications
      run: FE_IMAGE=${{ inputs.fe_image }} BE_IMAGE=${{ inputs.be_image }} docker-compose up -d
    - name: Run tests
      run: ./gradlew test
