name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      fe_image:
        default: 'evercoinx/faraway:nft-collection-deployer-frontend'
        required: true
        type: string
      be_image:
        default: 'evercoinx/faraway:nft-collection-deployer-backend'
        required: true
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Build Applications
      run: FE_IMAGE=${{ inputs.fe_image }} BE_IMAGE=${{ inputs.be_image }} docker-compose up -d
    - name: Run tests
      env: 
        FIRST_S: ${{ secrets.FIRST_S }}
        SECOND_S: ${{ secrets.SECOND_S }}
        THIRD_S: ${{ secrets.THIRD_S }}
        FOURTH_S: ${{ secrets.FOURTH_S }}
        FIFTH_S: ${{ secrets.FIFTH_S }}
        SIXTH_S: ${{ secrets.SIXTH_S }}
        SEVENTH_S: ${{ secrets.SEVENTH_S }}
        EIGHT_S: ${{ secrets.EIGHT_S }}
        NINTH_S: ${{ secrets.NINTH_S }}
        TENTH_S: ${{ secrets.TENTH_S }}
        ELEVENTH_S: ${{ secrets.ELEVENTH_S }}
        TWELFTH_S: ${{ secrets.TWELFTH_S }}
        PASSWORD: ${{ secrets.PASSWORD }}
        WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        RPC_TOKEN: ${{ secrets.RPC_TOKEN }}
      run: ./gradlew test --stacktrace --info
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report
        path: ${{ github.workspace }}/build/reports/tests/
