name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      fe_image:
        default: 'evercoinx/faraway:nft-collection-deployer-frontend'
        required: true
        type: string
      be_image:
        default: 'evercoinx/faraway:nft-collection-deployer-backend'
        required: true
        type: string

jobs:
  checkout_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: ls ${{ github.workspace }}

  build_applications:
    runs-on: ubuntu-latest
    steps:
    - name: Build Applications
    - run: ls ${{ github.workspace }}
    - run: FE_IMAGE=${{ inputs.fe_image }} BE_IMAGE=${{ inputs.be_image }} docker-compose up -d
  
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
    - run: ls ${{ github.workspace }}
    - run: ./gradlew test
